"use client";

import { useState } from "react";
import {
  ScanEye,
  ArrowLeft,
  CheckCircle,
  AlertTriangle,
  XCircle,
  FileWarning,
  Layers,
  AudioWaveform,
  Search,
} from "lucide-react";
import Link from "next/link";
import { UploadZone } from "@/components/UploadZone";
import { TrustScore } from "@/components/TrustScore";

interface MetadataSignal {
  tool: string;
  confidence: "high" | "medium" | "low";
  detail: string;
}

interface ForensicsResult {
  score: number;
  verdict: "likely_authentic" | "possibly_edited" | "likely_manipulated";
  signals: string[];
  metadata: MetadataSignal[];
  ela: {
    maxDeviation: number;
    avgDeviation: number;
    suspiciousRegions: number;
    isManipulated: boolean;
  };
  noise: {
    uniformity: number;
    isAIGenerated: boolean;
  };
}

const verdictConfig = {
  likely_authentic: {
    class: "verdict-original",
    label: "Likely Authentic",
    icon: CheckCircle,
  },
  possibly_edited: {
    class: "verdict-found",
    label: "Possibly Edited",
    icon: AlertTriangle,
  },
  likely_manipulated: {
    class: "verdict-scam",
    label: "Likely Manipulated",
    icon: XCircle,
  },
};

function getSignalIcon(signal: string) {
  if (signal.includes("No signs")) return CheckCircle;
  if (signal.includes("AI generation tool") || signal.includes("Noise pattern"))
    return XCircle;
  return AlertTriangle;
}

function getSignalColor(signal: string) {
  if (signal.includes("No signs")) return "var(--success)";
  if (signal.includes("AI generation tool") || signal.includes("likely"))
    return "var(--danger)";
  return "var(--warning)";
}

export default function ForensicsPage() {
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result, setResult] = useState<ForensicsResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleImageSelect = async (file: File) => {
    setIsAnalyzing(true);
    setResult(null);
    setError(null);

    try {
      const formData = new FormData();
      formData.append("image", file);

      const response = await fetch("/api/forensics", {
        method: "POST",
        body: formData,
      });

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || "Analysis failed");
      }

      setResult(await response.json());
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "An unexpected error occurred"
      );
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleReset = () => {
    setResult(null);
    setError(null);
  };

  return (
    <div className="min-h-screen pt-16">
      <div
        className="relative"
        style={{
          background:
            "radial-gradient(ellipse at 50% 0%, rgba(0,229,204,0.06) 0%, transparent 50%)",
        }}
      >
        <div className="max-w-4xl mx-auto px-6 pt-12 pb-8">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-sm mb-6 transition-colors"
            style={{ color: "var(--text-tertiary)" }}
            onMouseEnter={(e) =>
              (e.currentTarget.style.color = "var(--accent)")
            }
            onMouseLeave={(e) =>
              (e.currentTarget.style.color = "var(--text-tertiary)")
            }
          >
            <ArrowLeft size={14} />
            Back to Home
          </Link>

          <h1
            className="text-2xl font-bold mb-3"
            style={{
              fontFamily: "var(--font-display)",
              letterSpacing: "-0.02em",
            }}
          >
            AI / Photoshop Detection
          </h1>
          <p
            className="text-sm"
            style={{ color: "var(--text-secondary)", maxWidth: "540px" }}
          >
            Upload a product photo to check if it was generated by AI or
            manipulated with editing software. Uses metadata analysis, error
            level analysis, and noise pattern detection.
          </p>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-6 pb-20">
        {/* Upload */}
        <div className="mb-8">
          <UploadZone
            onImageSelect={handleImageSelect}
            disabled={isAnalyzing}
          />
        </div>

        {/* Loading */}
        {isAnalyzing && (
          <div className="card p-12 text-center fade-in">
            <div className="relative inline-flex items-center justify-center mb-6">
              <div
                className="w-20 h-20 rounded-full pulse-ring"
                style={{
                  border: "2px solid var(--accent)",
                  opacity: 0.3,
                  position: "absolute",
                }}
              />
              <div
                className="w-16 h-16 rounded-full flex items-center justify-center"
                style={{
                  background: "var(--accent-glow)",
                  border: "1px solid var(--border-accent)",
                }}
              >
                <ScanEye
                  size={24}
                  style={{ color: "var(--accent)" }}
                  className="animate-pulse"
                />
              </div>
            </div>

            <h3
              className="text-lg font-semibold mb-2"
              style={{ fontFamily: "var(--font-display)" }}
            >
              Analyzing Image
            </h3>
            <p
              className="text-sm mb-6"
              style={{ color: "var(--text-secondary)" }}
            >
              Running forensic analysis...
            </p>

            <div className="verify-pulse flex items-center justify-center gap-2">
              <span />
              <span />
              <span />
            </div>

            <div
              className="mt-8 flex flex-col gap-2 max-w-xs mx-auto text-left"
              style={{ fontFamily: "var(--font-mono)", fontSize: "12px" }}
            >
              {[
                "Scanning EXIF metadata...",
                "Checking for AI signatures...",
                "Running Error Level Analysis...",
                "Analyzing noise patterns...",
                "Generating forensics report...",
              ].map((step, i) => (
                <div
                  key={i}
                  className="flex items-center gap-2 fade-in"
                  style={{
                    animationDelay: `${i * 0.5}s`,
                    color: "var(--text-tertiary)",
                  }}
                >
                  <span
                    className="w-1.5 h-1.5 rounded-full"
                    style={{ background: "var(--accent)", opacity: 0.6 }}
                  />
                  {step}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Error */}
        {error && (
          <div
            className="card p-6 fade-in-up"
            style={{ borderColor: "rgba(239, 68, 68, 0.3)" }}
          >
            <p className="text-sm" style={{ color: "var(--danger)" }}>
              {error}
            </p>
            <button
              onClick={handleReset}
              className="btn-secondary mt-4"
              style={{ fontSize: "13px", padding: "8px 16px" }}
            >
              Try Again
            </button>
          </div>
        )}

        {/* Results */}
        {result && (
          <div className="space-y-6 fade-in-up">
            {/* Main Result Card */}
            <div className="card" style={{ overflow: "hidden" }}>
              <div
                className="px-6 py-4 flex items-center justify-between"
                style={{
                  borderBottom: "1px solid var(--border)",
                  background: "var(--bg-tertiary)",
                }}
              >
                <span
                  className={`verdict-badge ${verdictConfig[result.verdict].class}`}
                >
                  {(() => {
                    const Icon = verdictConfig[result.verdict].icon;
                    return <Icon size={14} />;
                  })()}
                  {verdictConfig[result.verdict].label}
                </span>
              </div>

              <div className="p-6">
                <div className="flex flex-col md:flex-row items-start gap-8">
                  <div className="flex-shrink-0">
                    <TrustScore score={result.score} size="lg" />
                  </div>

                  <div className="flex-1 min-w-0">
                    {/* Signals */}
                    <h3
                      className="text-xs font-semibold uppercase tracking-wider mb-3"
                      style={{
                        color: "var(--text-tertiary)",
                        fontFamily: "var(--font-mono)",
                      }}
                    >
                      Findings
                    </h3>
                    <div className="flex flex-col gap-2 mb-6">
                      {result.signals.map((signal, i) => {
                        const Icon = getSignalIcon(signal);
                        return (
                          <div
                            key={i}
                            className="flex items-start gap-3 p-3 rounded-lg"
                            style={{ background: "var(--bg-tertiary)" }}
                          >
                            <Icon
                              size={16}
                              className="mt-0.5 flex-shrink-0"
                              style={{ color: getSignalColor(signal) }}
                            />
                            <span
                              className="text-sm"
                              style={{ color: "var(--text-primary)" }}
                            >
                              {signal}
                            </span>
                          </div>
                        );
                      })}
                    </div>

                    {/* Metadata Signals */}
                    {result.metadata.length > 0 && (
                      <div className="mb-6">
                        <h3
                          className="text-xs font-semibold uppercase tracking-wider mb-3 flex items-center gap-2"
                          style={{
                            color: "var(--text-tertiary)",
                            fontFamily: "var(--font-mono)",
                          }}
                        >
                          <FileWarning size={13} />
                          Metadata Signals
                        </h3>
                        {result.metadata.map((m, i) => (
                          <div
                            key={i}
                            className="flex items-start gap-3 p-3 rounded-lg mb-2"
                            style={{ background: "var(--bg-tertiary)" }}
                          >
                            <span
                              className="px-2 py-0.5 rounded text-xs font-semibold flex-shrink-0"
                              style={{
                                background:
                                  m.confidence === "high"
                                    ? "var(--danger-dim)"
                                    : m.confidence === "medium"
                                    ? "var(--warning-dim)"
                                    : "var(--bg-elevated)",
                                color:
                                  m.confidence === "high"
                                    ? "var(--danger)"
                                    : m.confidence === "medium"
                                    ? "var(--warning)"
                                    : "var(--text-tertiary)",
                                fontFamily: "var(--font-mono)",
                              }}
                            >
                              {m.confidence}
                            </span>
                            <span
                              className="text-sm"
                              style={{ color: "var(--text-secondary)" }}
                            >
                              {m.detail}
                            </span>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </div>

            {/* Technical Details */}
            <div className="grid md:grid-cols-2 gap-4">
              {/* ELA Card */}
              <div className="card p-5">
                <div className="flex items-center gap-2 mb-4">
                  <Layers size={16} style={{ color: "var(--accent)" }} />
                  <h3
                    className="text-xs font-semibold uppercase tracking-wider"
                    style={{
                      color: "var(--text-secondary)",
                      fontFamily: "var(--font-mono)",
                    }}
                  >
                    Error Level Analysis
                  </h3>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <p
                      className="text-2xl font-bold"
                      style={{
                        fontFamily: "var(--font-mono)",
                        color: result.ela.isManipulated
                          ? "var(--danger)"
                          : "var(--accent)",
                      }}
                    >
                      {result.ela.suspiciousRegions}%
                    </p>
                    <p
                      className="text-xs"
                      style={{ color: "var(--text-tertiary)" }}
                    >
                      Suspicious Regions
                    </p>
                  </div>
                  <div>
                    <p
                      className="text-2xl font-bold"
                      style={{
                        fontFamily: "var(--font-mono)",
                        color: "var(--text-primary)",
                      }}
                    >
                      {result.ela.avgDeviation}
                    </p>
                    <p
                      className="text-xs"
                      style={{ color: "var(--text-tertiary)" }}
                    >
                      Avg Deviation
                    </p>
                  </div>
                </div>
                <div
                  className="mt-4 h-2 rounded-full overflow-hidden"
                  style={{ background: "var(--bg-elevated)" }}
                >
                  <div
                    className="h-full rounded-full"
                    style={{
                      width: `${Math.min(100, result.ela.suspiciousRegions * 3)}%`,
                      background: result.ela.isManipulated
                        ? "var(--danger)"
                        : "var(--accent)",
                    }}
                  />
                </div>
                <p
                  className="mt-2 text-xs"
                  style={{ color: "var(--text-tertiary)" }}
                >
                  {result.ela.isManipulated
                    ? "High ELA variance detected -- regions may have been edited or composited"
                    : "ELA levels appear consistent across the image"}
                </p>
              </div>

              {/* Noise Card */}
              <div className="card p-5">
                <div className="flex items-center gap-2 mb-4">
                  <AudioWaveform
                    size={16}
                    style={{ color: "var(--accent)" }}
                  />
                  <h3
                    className="text-xs font-semibold uppercase tracking-wider"
                    style={{
                      color: "var(--text-secondary)",
                      fontFamily: "var(--font-mono)",
                    }}
                  >
                    Noise Analysis
                  </h3>
                </div>
                <div>
                  <p
                    className="text-2xl font-bold"
                    style={{
                      fontFamily: "var(--font-mono)",
                      color: result.noise.isAIGenerated
                        ? "var(--danger)"
                        : "var(--accent)",
                    }}
                  >
                    {result.noise.uniformity}%
                  </p>
                  <p
                    className="text-xs"
                    style={{ color: "var(--text-tertiary)" }}
                  >
                    Noise Uniformity
                  </p>
                </div>
                <div
                  className="mt-4 h-2 rounded-full overflow-hidden"
                  style={{ background: "var(--bg-elevated)" }}
                >
                  <div
                    className="h-full rounded-full"
                    style={{
                      width: `${result.noise.uniformity}%`,
                      background: result.noise.isAIGenerated
                        ? "var(--danger)"
                        : "var(--accent)",
                    }}
                  />
                </div>
                <p
                  className="mt-2 text-xs"
                  style={{ color: "var(--text-tertiary)" }}
                >
                  {result.noise.isAIGenerated
                    ? "Noise is unnaturally uniform -- typical of AI-generated images"
                    : "Noise patterns appear natural -- consistent with camera-captured photos"}
                </p>
              </div>
            </div>

            {/* How It Works */}
            <div
              className="card p-5"
              style={{ borderLeft: "3px solid var(--accent)" }}
            >
              <div className="flex items-center gap-2 mb-3">
                <Search size={14} style={{ color: "var(--accent)" }} />
                <h3
                  className="text-xs font-semibold uppercase tracking-wider"
                  style={{
                    color: "var(--text-secondary)",
                    fontFamily: "var(--font-mono)",
                  }}
                >
                  How This Works
                </h3>
              </div>
              <div
                className="grid md:grid-cols-3 gap-4 text-xs"
                style={{ color: "var(--text-secondary)" }}
              >
                <div>
                  <p className="font-semibold mb-1" style={{ color: "var(--text-primary)" }}>
                    Metadata Scan
                  </p>
                  <p>
                    Checks embedded EXIF data for signatures of AI tools
                    (DALL-E, Midjourney) and editing software (Photoshop, GIMP).
                  </p>
                </div>
                <div>
                  <p className="font-semibold mb-1" style={{ color: "var(--text-primary)" }}>
                    Error Level Analysis
                  </p>
                  <p>
                    Re-compresses the image and compares error patterns.
                    Manipulated regions show different error levels than
                    originals.
                  </p>
                </div>
                <div>
                  <p className="font-semibold mb-1" style={{ color: "var(--text-primary)" }}>
                    Noise Detection
                  </p>
                  <p>
                    AI images have unnaturally uniform noise. Real camera photos
                    have natural sensor noise that varies across the frame.
                  </p>
                </div>
              </div>
            </div>

            <div className="text-center">
              <button onClick={handleReset} className="btn-secondary">
                Analyze Another Image
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
